---
driver:
  name: vagrant
  ssh:
    insert_key: false

transport:
  max_ssh_sessions: 6

provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: ./
  require_ansible_repo: true
  ansible_verbose: true
  idempotency_test: true

verifier:
  name: inspec
  sudo_path: true

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: ubuntu-22.04
  - name: debian-8
  - name: debian-9
  - name: debian-10
  - name: centos-7
  - name: centos-8
  - name: amazonlinux-2

suites:
  - name: standard
    provisioner:
      playbook: test/integration/standard.yml
      additional_copy_path:
        - "."
    run_list:
    attributes:
    verifier:
      inspec_tests: 
        - test/integration/standard/serverspec/default_spec.rb




  # - name: standard-6x
  #   provisioner:
  #     playbook: test/integration/standard-6x.yml
  #     additional_copy_path:
  #       - "."
  #   run_list:
  #   attributes:
  # - name: multi
  #   provisioner:
  #     playbook: test/integration/multi.yml
  #     additional_copy_path:
  #       - "."
  #   run_list:
  #   attributes:
  # - name: config
  #   provisioner:
  #     playbook: test/integration/config.yml
  #     additional_copy_path:
  #       - "."
  #   run_list:
  #   attributes:
  # - name: oss
  #   provisioner:
  #     playbook: test/integration/oss.yml
  #     additional_copy_path:
  #       - "."
  #   run_list:
  #   attributes:
